
name: multi-job
on:  workflow_dispatch
jobs:
  build-on-windows:
    runs-on: windows-latest
    steps:
      - name: step1 - Log the pre-build disc space 
        run: ls    
      - name: step 2 - check the the master github branch 
        uses: actions/checkout@v2
      - name: step 3 - set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: step 4 - check widnows execution policy
        run: |
          echo windows exectionpolicy is
          Get-ExecutionPolicy
      - name: Step 5 -  list of windows env variables 
        run: env 
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps: 
      - name: step1 - Log pre-build disc sapce
        run: df
        
    
